[package]
name = "pinconf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde_derive = "1.0.130"
serde = "1.0.130"
clap = { version = "2.32.0", features = ["yaml"] }
